name : Quiz Check

on:
  push:
    branches:
      - main
      
jobs:
  black-check:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black-check
        run: 
          black --diff .
          black --check -v .

  pylint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: pylint myquiz.py
